version: '2.27'

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    init: true
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      inception:
    environment:
      - NGINX_HOST=sagnshin.42.fr
      - NGINX_PORT=443
    restart: always

  wordpress:
    build: requirements/wordpress/.
    init: true
    container_name: wp-php
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress:/var/www/html
    networks:
      inception:
    restart: always
    env_file:
      - .env

  mariadb:
    build: requirements/mariadb/.
    init: true
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      inception:
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: always

networks:
  inception:


volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /root/data/mariadb
      o: bind
      type: none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /root/data/wordpress
      o: bind
      type: none

