version: '2.27'

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - ./web:/var/www/html
    networks:
      inception:
    environment:
      - NGINX_HOST=sagnshin.42.fr
      - NGINX_PORT=443
    restart: always

  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./web:/var/www/html
    networks:
      inception:
    restart: always
    env_file:
      - .env

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    volumes:
      - ./database:/var/lib/mysql
    networks:
      inception:
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: always

networks:
  inception:
